version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependency-update :arrow_up:"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule: 
      interval: "daily"
    commit-message:
      prefix: "dependency-update :arrow_up:"  